server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/neovote_demo_iv #NOMBRE_BD
    username: root #PLACEHOLDER
    password: 852456msql #PLACEHOLDER

  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop

  mvc:
    encoding:
      charset: UTF-8
    static-path-pattern: /static/**
    hiddenmethod:
      filter:
        enabled: true

  template:
    cache: false

  thymeleaf:
    encoding: UTF-8
    enabled: true
    cache: false

  messages:
    basename: verificationMessages, validationMessages
    fallback-to-system-locale: true
    encoding: UTF-8

  mail:
    host: smtp.gmail.com
    port: 587 # port 587 is for encrypted sessions, 25 is for plain/text
    username: lautaro.pipe@gmail.com #HERE GOES THE GMAIL USERNAME
    password: paay qfjt agmg afoz #HERE GOES THE 'APPLICATION PASSWORD' FOR THE GMAIL
    transport:
      protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true # Some SMTP servers require a TLS connection

logging:
  level:
    root: INFO
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
      springframework:
        web: DEBUG
        security:
          web:
            FilterChainProxy: DEBUG
      mapstruct: DEBUG
    com:
      digiteo: DEBUG

com:
  digiteo:
    secure:
      token:
        expSeconds: 21600

site:
  base:
    url:
      http: http://localhost:8080
      https: http://localhost:8080
